# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
    exclude: |
      (?x)^(.*\.idea.*)$
  - id: check-yaml
    exclude: |
      (?x)^(.*templates.*|.github.*)$
    args:
    - --unsafe  # allow custom !include constructors
  - id: debug-statements
  - id: detect-aws-credentials
    args:
    - --allow-missing-credentials  # allow hook to pass when no creds file is available
  - id: end-of-file-fixer
  - id: file-contents-sorter
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args:
    - --py310-plus
- repo: https://github.com/PyCQA/autoflake
  rev: v2.0.0
  hooks:
  - id: autoflake
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/asottile/yesqa
  rev: v1.4.0
  hooks:
  - id: yesqa
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-yaml
    exclude: |
      (?x)^(.*templates.*|.github.*)$
    args:
    - --autofix
  - id: pretty-format-toml
    exclude: |
      (?x)^(poetry\.lock)$
    args:
    - --autofix
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    exclude: |
      (?x)^(.*templates.*)$
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shellcheck
